/**
 * AUTH-02 (T-03, D-4): derive the common-password list from SecLists' NCSC file.
 * Run once by hand with a downloaded copy; the output is committed, so builds never download.
 *
 *   npx tsx scripts/derive-common-passwords.ts <100k-most-used-passwords-NCSC.txt> <SecLists commit sha>
 *
 * Keeps printable-ASCII entries whose folded form (lower case, no whitespace, as
 * password-rules.ts compares) has 12 or more characters; shorter ones fail the length rule.
 * Entries with other characters in this file are mis-encoded Cyrillic and are dropped.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const [input, commit] = process.argv.slice(2);
if (!input || !/^[0-9a-f]{40}$/.test(commit ?? "")) {
  console.error("Usage: tsx scripts/derive-common-passwords.ts <NCSC file> <40-character SecLists commit sha>");
  process.exit(1);
}

const bytes = readFileSync(input);
const entries = [...new Set(
  bytes.toString("utf8").split(/\r?\n/)
    .filter((line) => /^[\x20-\x7e]+$/.test(line))
    .map((line) => line.toLowerCase().replace(/\s+/g, ""))
    .filter((entry) => entry.length >= 12),
)].sort();

const output = path.resolve("src", "lib", "auth", "common-passwords-seclists.ts");
writeFileSync(output, `/**
 * Generated by scripts/derive-common-passwords.ts. Do not edit by hand.
 *
 * Source: SecLists, Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt
 * at commit ${commit}
 * (https://github.com/danielmiessler/SecLists), SHA-256 ${createHash("sha256").update(bytes).digest("hex")}.
 * ${entries.length} entries: printable ASCII, folded (lower case, no whitespace), 12+ characters.
 *
 * MIT License
 *
 * Copyright (c) 2018 Daniel Miessler
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
export const SECLISTS_COMMON_PASSWORDS: readonly string[] = ${JSON.stringify(entries, null, 0).replace(/","/g, "\",\n  \"").replace(/^\[/, "[\n  ").replace(/\]$/, ",\n]")};
`);
console.log(`Wrote ${entries.length} entries to ${path.relative(process.cwd(), output)}`);
